#!/usr/bin/env python

import hydra
from omegaconf import DictConfig, OmegaConf

import logging
import socket
import importlib

import time

import random
import numpy as np
import pandas as pd
from copy import deepcopy

import sys, os

file_dir1 = os.path.dirname(os.path.dirname(__file__))
file_dir2 = os.path.dirname(__file__)
sys.path.append(file_dir1)
sys.path.append(file_dir2)


from ncmw.utils.utils_io import (
    get_models,
    get_result_path,
    SEPERATOR,
    save_model,
    get_model_paths,
)
from ncmw.setup_models import *

from runs import run_setup as run

import cobra


@hydra.main(config_path="../data/hydra", config_name="config.yaml")
def run_setup(cfg: DictConfig) -> None:
    run(cfg)


if __name__ == "__main__":
    run_setup()
