#!/usr/bin/env python

import hydra
from omegaconf import DictConfig, OmegaConf

import logging
import socket
import importlib

import time

import random
import numpy as np
import pandas as pd
import json

import sys, os


file_dir1 = os.path.dirname(os.path.dirname(__file__))
file_dir2 = os.path.dirname(__file__)
sys.path.append(file_dir1)
sys.path.append(file_dir2)

from ncmw.visualization import (
    plot_pairwise_growth_relation_per_weight,
    plot_community_interaction,
    plot_posterior_samples_for_observations,
    plot_community_uptake_graph,
    plot_species_interaction,
)

from ncmw.utils.utils_io import (
    get_models,
    get_result_path,
    SEPERATOR,
    save_model,
    get_model_paths,
    get_mediums,
)
from ncmw.community import (
    BagOfReactionsModel,
    ShuttleCommunityModel,
    compute_fair_weights,
    compute_community_summary,
    compute_dominant_weights,
)

import cobra

from runs import run_community as run


@hydra.main(config_path="../data/hydra", config_name="config.yaml")
def run_community(cfg: DictConfig) -> None:
    run(cfg)


if __name__ == "__main__":
    run_community()
