#!/usr/bin/env python

import hydra
from omegaconf import DictConfig, OmegaConf

import logging
import socket
import importlib

import time

import random
import numpy as np
import pandas as pd
import json

import sys, os

file_dir1 = os.path.dirname(os.path.dirname(__file__))
file_dir2 = os.path.dirname(__file__)
sys.path.append(file_dir1)
sys.path.append(file_dir2)


from ncmw.analysis import (
    compute_fvas,
    jaccard_similarity_matrices,
    compute_COMPM,
    table_ex_transport,
    sekretion_uptake_fva,
    sekretion_uptake_fba,
    compute_uptake_sekretion_table,
)
from ncmw.visualization import (
    plot_full_fva,
    plot_medium_fva_range,
    jacard_index_similarity_heatmap,
    plot_scaled_medium_growth,
    uptake_sekretion_venn_diagrams,
)

from ncmw.utils import (
    get_models,
    get_result_path,
    SEPERATOR,
    save_model,
    get_model_paths,
)

from runs import run_analysis as run


@hydra.main(config_path="../data/hydra", config_name="config.yaml")
def run_analysis(cfg: DictConfig) -> None:
    run(cfg)


if __name__ == "__main__":
    run_analysis()
